### PR TITLE
Sync Github with Drupal module

### PR DESCRIPTION
**Pull request by joshcanhelp**
Addresses #86 

Ping @rob3000

### CODE REVIEW

**Comment by rob3000** [comment]
Hey @joshcanhelp Wanting to kick this back off again to get the github and drupal.org in sync again,  Whats left to do on this PR? Anything i need to be aware of?

**Comment by joshcanhelp** [comment]
Thanks for checking back in @rob3000. I would love to push this forward but had higher priority tasks land on my end. 

I would guess I'm about half done with the code here. I ran a diff between the DO module and this one and just made line-by-line changes. It occurred to me, though, that a PR this big will be a huge review for whomever has to do that on our end so I was considering breaking it into smaller pieces. 

As I mentioned to you before, the main thing for us is making sure that this works with new tenants. The `master` branch here does but the DO module does not (relies on endpoints that have been deprecated for new users). 

If you're able to pick up where I left off, I can definitely keep some time free to review and assist. If you think we should go at it a different way (piece by piece or however), I'm totally open to suggestions! 

Thank you again!

**Comment by rob3000** [comment]
Hey @joshcanhelp If thats the case and master is more up to date with the relevant endpoints,0 I think in order to tackle this we do it in the following steps:

1 - Update master (github) to adhere drupal coding standards.
2 - Apply fixes (if any) from D.O
3 - Sync D.O with Github.

I think doing the following would be a fast way of getting the modules back in sync. I'd suggest we do them as seperate PR's so that its easier to review.

Also i was wondering if you had thought of adding some form of CI for github to auto test for drupal coding standards and best practice? Something like CircleCI or TravisCI (Both free for Github code)

- https://travis-ci.org/
- https://circleci.com/pricing/

Could look to automate this to so that when a release is created here could autoSync to D.O

Thoughts?

**Comment by joshcanhelp** [comment]
@rob3000 - That all sounds great. Would you be willing to take on the bulk of the DO standards work? I'm happy to help with the Auth0-specific stuff and can review your PRs as they come in. If that's amenable, I'd suggest doing a PR for each file/functional component so it's a little easier to get through those reviews. I'll check the code, test the PR locally, and provide feedback. 

As for CI ... we use Travis on a number of our OSS projects in this GH org and have moved a number of others to CircleCI. Just point me in the right direction on how to get that setup for Drupal and I'll handle the integration. 

Thanks!

**Comment by rob3000** [comment]
Hey @joshcanhelp Yep happy to take that task and will create a PR per file.

I'll have a look into how to push from githhub to D.O but for drupal coding standards you can use the https://www.drupal.org/project/coder project which can be pulled in via composer (https://cgit.drupalcode.org/coder/tree/composer.json) which has all the sniffs for PHPCS.

It should just be a matter of doing:
`composer require drupal/coder --dev`
Then for running it doing `bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer/`

**Comment by rob3000** [comment]
Hey @joshcanhelp 

So i've tagged you in a few PR's :) These are just to change the files to meet drupals coding standards. Once these are done i can move onto the Best Practices part which is where more of the more in depth changes come from. Let me know when you'd like me to tackle the best practices.

PRS:
https://github.com/auth0/auth0-drupal/pull/100
https://github.com/auth0/auth0-drupal/pull/101
https://github.com/auth0/auth0-drupal/pull/102
https://github.com/auth0/auth0-drupal/pull/103
https://github.com/auth0/auth0-drupal/pull/104
https://github.com/auth0/auth0-drupal/pull/105

I'm still going with the `Controller/AuthController.php` That's a big one.

**Comment by joshcanhelp** [comment]
Awesome @rob3000, thank you! I've been setting up phpcs for our other repos so all that is familiar. I can look into pushing to DO with Jenkins. I have to set that up for our WordPress module as well and I'l sure a lot of the knowledge will pass over. 

I'll try to get these PRs pushed through today!

**Pull request closed without merging**
